version: "3.8"

services:
  doctor-directory-api:
    container_name: doctor-directory-api
    build: ./
    command: npm run dev
    working_dir: /home/server
    environment:
      DB_URI: mongodb://root:pass@mongodb/
      SECRET_WORD: addsecretWorDHeRe
    ports:
      - "3000:3000"
    volumes:
      - ./:/home/server
    depends_on:
      - mongodb
    networks:
      - doctor-directory-network

  mongodb:
    container_name: mongodb
    image: mongo:8.0
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo-data:/data/db
    networks:
      - doctor-directory-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8080:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_BASICAUTH_USERNAME=raouf
      - ME_CONFIG_BASICAUTH_PASSWORD=password
    depends_on:
      - mongodb
    networks:
      - doctor-directory-network

volumes:
  mongo-data:

networks:
  doctor-directory-network:
    driver: bridge
